### ISSUE TITLE
How to access rootPath from within application?

### ISSUE THREAD

**Issue by AlexCppns** [aymericbeaumet/metalsmith-define#1]
I have the following gulp task:
```
 app.use(
        msDefine({
            production: false,
            rootPath: '/'
        })
    );

    app.use(
        msIf(
            gutil.env.config === 'release',
            msDefine({
                production: true,
                rootPath: '/styleguide/'
            })
        )
    );
```

In my angular component, I wanna do something like:
```
import stuff from 'stuff';

export class IconCtrl ...
  ...
  _getIconPath(name: string, size: string): string {
       
        switch (this.version) {
            case 'current':
                return `${stuff.rootPath()}/current/icn-${name}-${size}.svg`;
            default:
                return `${stuff.rootPath()}/legacy/${name}.svg`;
        }
    }
   ...
```

How do I access the rootPath?

**Comment by aymericbeaumet** [comment]
I think metalsmith now [natively supports this feature](http://www.metalsmith.io/#metadata-debugging), making this plugin obsolete.

Also you would need a templating plugin to replace your placeholders with the metadata you define. Give a look at: https://github.com/ismay/metalsmith-layouts

**Comment by AlexCppns** [comment]
Alright, I am not sure how that answers my question, I'll try to find a workaround. By the way, this is legacy code, refactoring would be hard.

**Comment by aymericbeaumet** [comment]
You want to access a variable you define in metalsmith in one of your Angular files, afaik you could use a metalsmith layout to inject what you defined with metalsmith define.

If that's not what you meant, can you give more details? Thanks
