### ISSUE TITLE
What extra features does this plugin provide over metalsmith.metadata() ? 

### ISSUE THREAD

**Issue by webketje** [aymericbeaumet/metalsmith-define#6]
Hi, 

Could you explain how this plugin provides added value over `metalsmith.metadata({ ... })`?
It seems to do exactly the same? 
Or perhaps add a deprecation notice if the features have been added to the core in the meantime?

**Comment by aymericbeaumet** [comment]
Hey Kevin, thanks for the heads up! It's true that the (new?) metadata method overlaps this plugin in some ways, I've updated the documentation to reflect how metalsmith-define could still have value for some people (https://github.com/aymericbeaumet/metalsmith-define/commit/621753cc6d4e247689077b630e630022a7b45713).
